version: "3"
services:
  selenium:
    image: selenium/standalone-chrome:115.0
    ports:
      - 4444:4444
      - 7900:7900 # novnc
    shm_size: 2gb
  app:
    build: .
    depends_on:
      - selenium
    volumes:
      - ./src:/app
    environment:
      SELENIUM_URL: http://selenium:4444/wd/hub
      LOGIN_ID: 00T000
      LOGIN_PASSWORD: password
      EXCEL_PATH: ./textbook.xlsx
    tty: true
